# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170911_1747'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userinfo',
            table='user_info',
        ),
    ]
